base/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views #import this


urlpatterns = [

    path('account-user-profile/<str:pk>/', views.userProfile, name="user-profile"),

    path('agenda-create/', views.agendaCreate, name="agenda-create"),
    path('agenda-detail/<int:id>/', views.agendaDetail, name="agenda-detail"),
    path('hx/agenda-detail/<int:id>/', views.agendaDetail_HX, name="hx-agenda-detail"),
    path('agenda-update/<int:id>/', views.agendaUpdate, name="agenda-update"),
    path('agenda-delete/<int:id>/', views.agendaDelete, name="agenda-delete"),
    
    path('hx/agenda-create/<int:parent_id>/monday/', views.mondayCreateUpdate_HX, name="hx-monday-create"),
    path('hx/agenda-update/<int:parent_id>/monday/<int:id>/', views.mondayCreateUpdate_HX, name="hx-monday-update"),
    path('monday-delete/<int:parent_id>/monday/<int:id>/', views.mondayDelete, name="monday-delete"),

    path('hx/agenda-create/<int:parent_id>/tuesday/', views.tuesdayCreateUpdate_HX, name="hx-tuesday-create"),
    path('hx/agenda-update/<int:parent_id>/tuesday/<int:id>/', views.tuesdayCreateUpdate_HX, name="hx-tuesday-update"),
    path('tuesday-delete/<int:parent_id>/tuesday/<int:id>/', views.tuesdayDelete, name="tuesday-delete"),

    path('hx/agenda-create/<int:parent_id>/wednesday/', views.wednesdayCreateUpdate_HX, name="hx-wednesday-create"),
    path('hx/agenda-update/<int:parent_id>/wednesday/<int:id>/', views.wednesdayCreateUpdate_HX, name="hx-wednesday-update"),
    path('wednesday-delete/<int:parent_id>/wednesday/<int:id>/', views.wednesdayDelete, name="wednesday-delete"),

    path('hx/agenda-create/<int:parent_id>/thursday/', views.thursdayCreateUpdate_HX, name="hx-thursday-create"),
    path('hx/agenda-update/<int:parent_id>/thursday/<int:id>/', views.thursdayCreateUpdate_HX, name="hx-thursday-update"),
    path('thursday-delete/<int:parent_id>/thursday/<int:id>/', views.thursdayDelete, name="thursday-delete"),

    path('hx/agenda-create/<int:parent_id>/friday/', views.fridayCreateUpdate_HX, name="hx-friday-create"),
    path('hx/agenda-update/<int:parent_id>/thursday/<int:id>/', views.fridayCreateUpdate_HX, name="hx-friday-update"),
    path('friday-delete/<int:parent_id>/thursday/<int:id>/', views.fridayDelete, name="friday-delete"),

    path('hx/agenda-create/<int:parent_id>/saturday/', views.saturdayCreateUpdate_HX, name="hx-saturday-create"),
    path('hx/agenda-update/<int:parent_id>/saturday/<int:id>/', views.saturdayCreateUpdate_HX, name="hx-saturday-update"),
    path('saturday-delete/<int:parent_id>/saturday/<int:id>/', views.saturdayDelete, name="saturday-delete"),

    path('hx/agenda-create/<int:parent_id>/sunday/', views.sundayCreateUpdate_HX, name="hx-sunday-create"),
    path('hx/agenda-update/<int:parent_id>/sunday/<int:id>/', views.sundayCreateUpdate_HX, name="hx-sunday-update"),
    path('sunday-delete/<int:parent_id>/sunday/<int:id>/', views.sundayDelete, name="sunday-delete"),

    
    path('calendar/', views.dateOverlays, name="calendar"),
    
    
    
    path('', views.home, name="home"),







    path('group-settings/<str:pk>/', views.groupSettings, name="group-settings"),
    path('create-group/', views.createGroup, name="create-group"),
    path('update-group/<str:pk>/', views.updateGroup, name="update-group"),
    path('delete-group/<str:pk>/', views.deleteGroup, name="delete-group"),
    path('group-members/<str:pk>/', views.groupMembers, name="group-members"),
    path('settings-OH/', views.settingsOH, name="telegram-settings-OH"),
    path('settings-OH-update/', views.settingsOH_update, name="telegram-settings-OH-update"),
    path('settings-VM/', views.settingsVM, name="telegram-settings-VM"),
    path('settings-VM-update/', views.settingsVM_update, name="telegram-settings-VM-update"),
    path('settings-TZ/', views.settingsTZ, name="telegram-settings-TZ"),
    path('settings-TZ-update/', views.settingsTZ_update, name="telegram-settings-TZ-update"),
    path('account-auth/', views.auth, name="telegram"),
    path('account-auth-token/', views.token, name="token"),

]

new_telegram_bot_service/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    
    # path('register/', views.registerPage, name="register"),

    # path('password-change/',
    #     auth_views.PasswordChangeView.as_view(
    #         template_name='new_telegram_bot_service/password-change.html',
    #         success_url = '/'
    #     ),name='password_change'),

    path("password-change/", views.password_change, name="password-change"),

    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='new_telegram_bot_service/password-reset-done.html'
        ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="new_telegram_bot_service/password-reset-confirm.html"
        ), name='password_reset_confirm'),

    path('password-reset-complet/', auth_views.PasswordResetCompleteView.as_view(
        template_name='new_telegram_bot_service/password-reset-complet.html'
        ), name='password_reset_complete'), 

    path('password-reset/', views.password_reset_request, name="password_reset"),

]

base/models.py
from django.db import models
from django.contrib.auth.models import User
import pytz
from django.urls import reverse
from django.dispatch import receiver
from django.db.models.signals import (
    post_save,
    pre_save 
)

class Telegram(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    telegram_id = models.IntegerField(null=True, blank=True)
    token = models.IntegerField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Token:{self.token}"

class Group_type(models.Model):
    type = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.type

class Group(models.Model):
    admin = models.ForeignKey(User, on_delete=models.CASCADE) 
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    type = models.ForeignKey(Group_type, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.name

class Settings(models.Model):

    STATUS_CHOISES = [
        ('open', 'Open'),
        ('permanently closed', 'Permanently Closed'),
    ]

    DAYS_CHOISES = [
        ('everyday', 'Everyday'),
        ('weekdays', 'Weekdays'),
        ('weekends', 'Weekends'),
    ]

    TIME_CHOISES = [
        ('24 hours', '24 Hours'),
        ('set open and close time', 'Set Open and Close Time'),
    ]

    OPEN_TIME_CHOISES = [
        ('AM', (
            ('0', '0h'),
            ('1', '1h'),
            ('2', '2h'),
            ('3', '3h'),
            ('4', '4h'),
            ('5', '5h'),
            ('6', '6h'),
            ('7', '7h'),
            ('8', '8h'),
            ('9', '9h'),
            ('10', '10h'),
            ('11', '11h'),
        )),
        ('PM', (
            ('12', '12h'),
            ('13', '13h'),
            ('14', '14h'),
            ('15', '15h'),
            ('16', '16h'),
            ('17', '17h'),
            ('18', '18h'),
            ('19', '19h'),
            ('20', '20h'),
            ('21', '21h'),
            ('22', '22h'),
            ('23', '23h'),
        ))
    ]

    CLOSE_TIME_CHOISES = [
        ('AM', (
            ('0', '0h'),
            ('1', '1h'),
            ('2', '2h'),
            ('3', '3h'),
            ('4', '4h'),
            ('5', '5h'),
            ('6', '6h'),
            ('7', '7h'),
            ('8', '8h'),
            ('9', '9h'),
            ('10', '10h'),
            ('11', '11h'),
        )),
        ('PM', (
            ('12', '12h'),
            ('13', '13h'),
            ('14', '14h'),
            ('15', '15h'),
            ('16', '16h'),
            ('17', '17h'),
            ('18', '18h'),
            ('19', '19h'),
            ('20', '20h'),
            ('21', '21h'),
            ('22', '22h'),
            ('23', '23h'),
        ))
    ]

    NOTIFICATION_CHOISES = [
        ('on', 'On'),
        ('off', 'Off'),
    ]

    VOICE_MESSAGES_CHOISES = [
        ('inactivated','Inactivate'),
        ('activated','Activate')
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOISES,
        default='Open',
        help_text='''Select the status'''
        ) 
        
    time = models.CharField(
        max_length=50,
        choices=TIME_CHOISES,
        default='24 Hours',
        help_text='''Select the time''',
        blank=True,
        null=True
        ) 

    open_time = models.CharField(
        max_length=50,
        choices=OPEN_TIME_CHOISES,
        default='invalid',
        help_text='''Select the open time''',
        null=True

        ) 

    close_time = models.CharField(
        max_length=50,
        choices=CLOSE_TIME_CHOISES,
        default='invalid',
        help_text='''Select the close time''',
        null=True
        ) 

    days = models.CharField(
        max_length=50,
        choices=DAYS_CHOISES,
        default='Everyday',
        help_text='''Select the days''',
        blank=True,
        null=True
        )

    notification = models.CharField(
        max_length=50,
        choices=NOTIFICATION_CHOISES,
        default='Off',
        help_text='''Select the notification''',
        blank=True,
        null=True
        )

    timezone = models.CharField(
        max_length=128, 
        choices=[(tz, tz) for tz in pytz.common_timezones],
        default='America/Sao_Paulo',
        blank=True,
        null=True
        )

    voice_messages = models.CharField(
        max_length=50,
        choices=VOICE_MESSAGES_CHOISES,
        default='Inactivate',
        blank=True,
        null=True
        )

    voice_messages_notification = models.CharField(
        max_length=10,
        choices=NOTIFICATION_CHOISES,
        default='Off',
        blank=True,
        null=True
        )

    def __str__(self):
        return f'Opening_hours: {self.user}'

@receiver(post_save, sender=User)
def new_user_agenda_create(sender, instance, created, *args, **kwargs):
    if created:
        Agenda.objects.create(user=instance, name='Main') 

class Agenda(models.Model):

    INCREMENTS_CHOISES = [
        ('15','15 min'), ('30','30 min'), ('45', '45 min'), ('60', '60 min')
    ]

    class Meta:
        verbose_name_plural = 'agenda'

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    name = models.CharField(
        max_length=70,
        null=True
    )

    increments = models.CharField(
        max_length=50,
        choices=INCREMENTS_CHOISES,
        default='30 min',
        null=True
        )

    timezone = models.CharField(
        max_length=128, 
        choices=[(tz, tz) for tz in pytz.common_timezones],
        default='America/Sao_Paulo',
        blank=True,
        null=True
        ) 

    monday = models.BooleanField(
        default=True
    )

    tuesday = models.BooleanField(
        default=True
    )

    wednesday = models.BooleanField(
        default=True
    )

    thursday = models.BooleanField(
        default=True
    )

    friday = models.BooleanField(
        default=True
    )

    saturday = models.BooleanField(
        default=False
    )

    sunday = models.BooleanField(
        default=False
    )

    new = models.BooleanField(
        default=True,
        null=True
    )

    def __str__(self):
        return f'{self.user} - {self.name}'

    def get_agenda_detail_url(self):
        return reverse('agenda-detail', kwargs={'id':self.id})

    def get_agenda_update_url(self):
        return reverse('agenda-update', kwargs={'id':self.id})

    def get_agenda_delete_url(self):
        return reverse('agenda-delete', kwargs={'id':self.id})

    def get_hx_url(self):
        return reverse("hx-agenda-detail", kwargs={"id": self.id})

    def get_monday_schedules(self):
        return self.mondayschedules_set.all()

    def get_tuesday_schedules(self):
        return self.tuesdayschedules_set.all()

    def get_wednesday_schedules(self):
        return self.wednesdayschedules_set.all()

    def get_thursday_schedules(self):
        return self.thursdayschedules_set.all()

    def get_friday_schedules(self):
        return self.fridayschedules_set.all()

    def get_saturday_schedules(self):
        return self.saturdayschedules_set.all()

    def get_sunday_schedules(self):
        return self.sundayschedules_set.all()

@receiver(pre_save, sender=Agenda)
def new_agenda_create(sender, instance, *args, **kwargs):
    if instance.new == True:
        instance.sunday = False
        instance.monday = True
        instance.tuesday = True
        instance.wednesday = True
        instance.thursday = True
        instance.friday = True
        instance.saturday = False
        instance.increments = '30'
        instance.timezone = 'America/Sao_Paulo'

@receiver(post_save, sender=Agenda)
def new_agenda_create(sender, instance, created, *args, **kwargs):
    if created:
        new_agenda = instance
        MondaySchedules.objects.create(agenda=new_agenda, start_time='07:00', end_time='17:00')
        TuesdaySchedules.objects.create(agenda=new_agenda, start_time='07:00', end_time='17:00')
        WednesdaySchedules.objects.create(agenda=new_agenda, start_time='07:00', end_time='17:00')
        ThursdaySchedules.objects.create(agenda=new_agenda, start_time='07:00', end_time='17:00')
        FridaySchedules.objects.create(agenda=new_agenda, start_time='07:00', end_time='17:00')

class MondaySchedules(models.Model):

    class Meta:
        verbose_name = 'Monday'
        verbose_name_plural = 'monday'

    OPEN_TIME_CHOISES = [
        ('AM', (('00:00', '0:00'),('00:15', '0:15'),('00:30', '0:30'),('00:45', '0:45'),
                ('01:00', '1:00'),('01:15', '1:15'),('01:30', '1:30'),('01:45', '1:45'),
                ('02:00', '2:00'),('02:15', '2:15'),('02:30', '2:30'),('02:45', '2:45'),
                ('03:00', '3:00'),('03:15', '3:15'),('03:30', '3:30'),('03:45', '3:45'),
                ('04:00', '4:00'),('04:15', '4:15'),('04:30', '4:30'),('04:45', '4:45'),
                ('05:00', '5:00'),('05:15', '5:15'),('05:30', '5:30'),('05:45', '5:45'),
                ('06:00', '6:00'),('06:15', '6:15'),('06:30', '6:30'),('06:45', '6:45'),
                ('07:00', '7:00'),('07:15', '7:15'),('07:30', '7:30'),('07:45', '7:45'),
                ('08:00', '8:00'),('08:15', '8:15'),('08:30', '8:30'),('08:45', '8:45'),
                ('09:00', '9:00'),('09:15', '9:15'),('09:30', '9:30'),('09:45', '9:45'),
                ('10:00', '10:00'),('10:15', '10:15'),('10:30', '10:30'),('10:45', '10:45'),

base/templates/base/account-auth.html
{% extends 'main.html' %}

{% block content %}

<style>
    .bot-container{
      display: grid;
      grid-template-columns: 1fr 1fr 5fr 1fr;
  
    }
    .bot-container2{
      display: grid;
      grid-template-columns: 5fr;
  
    }
    .telegram-settings-container{
      display: grid;
      grid-template-columns: 1fr 6fr 1fr;

    }
    .telegram-settings-container2{
      display: grid;
      grid-template-columns: 6fr;

    }
    .telegram-settings-container3{
      display: grid;
      grid-template-columns: 1fr 5fr;

    }
    .telegram-settings-container4{
      display: grid;
      grid-template-columns: 4fr 1fr;

    }
    .telegram-settings-container5{
      display: grid;
      grid-template-columns: 1fr 22fr 4fr 1fr;

    }
    .telegram-settings-container6{
      display: grid;
      grid-template-columns: 1fr 28fr 1fr;

    }
    .telegram-settings-container7{
      border-style: solid;

    }
</style>


<div class="telegram-settings-container">

    <div></div>
  
    <div>
    
      <div class="telegram-settings-container2">
        <div>
          <spam style="float:left">
            <h1>Account</h1>
          </spam>
          <spam style="float:right">
          </spam>
        </div>
      </div> 
      <hr>
  
      <div class="telegram-settings-container3">
          
        <div>    
          <h3><a href="{% url 'user-profile' user.id %}">Profile</a></h3>
          <h3>Telegram Auth</h3> 
          <h3><a href="">Calendar conections</a></h3>
        </div>
      
        <div>
          <div class="telegram-settings-container4">
            <div>
              <h1>Auth</h1>
            </div>
            <div>

            </div>
          </div>
          <hr>            
          <div class="telegram-settings-container2">
              <div>
                <spam style="float:left">
                    <h3>Token</h3>
                </spam>
                <spam style="float:right">
                    <form method="POST" action="{% url 'token' %}">
                        {% csrf_token %}
                        <h3><button>Token</button></h3>    
                    </form>
                </spam>
              </div>
                                
          </div>
          <hr>
            
      
        </div>
  
    </div>
    
  
    <div></div>
          
  </div>

{% endblock content %}

base/templates/base/agenda-detail.html
{% extends 'main.html' %}

{% block content %}

<style>
  .agenda-detail-container{
    display: grid;
    /* grid-template-columns: 1fr 4fr 1fr; */

  }
  .agenda-detail-title{
    display: grid;
    grid-template-columns: 4fr;

  }
  .agenda-detail-list{
    display: grid;
    grid-template-columns: 1fr 6fr;

  }
  .agenda-detail-form{
    display: grid;
    grid-template-columns: 3fr 1fr;

  }
  .agenda-detail-weekly-squedules{
    display: grid;
    grid-template-columns: 1fr 14fr 14fr 1fr;
    border-style: solid;
    border-width: 1px;

  }
  .agenda-detail-weekly-squedules-form{
    display: grid;
    grid-template-columns: 1fr 11fr 4fr 1fr;
    

  }
  .htmx-indicator{
    display: none;

  }
  .htmx-request .htmx-indicator{
    display: block;

  }

</style>

<div hx-get="{{ hx_url }}" hx-trigger="load delay:0.5s">
  
  <div class="agenda-detail-container">
    <div></div>
    <div class="htmx-indicator"><h3>Loading...</h3></div>
    <div></div>
  </div>
    
</div>

{% endblock content %}

base/templates/base/agenda-update.html
{% extends 'main.html' %}

{% block content %}

<style>
    .create-update-container{
      display: grid;
      grid-template-columns: 1fr 6fr 1fr;
  
    }
    .weekday-container{
        display: grid;
        grid-template-columns: 1.5fr 3fr 1.5fr 1fr;
    }
    .weekday-inline-container{
        display: grid;
        grid-template-columns: 2fr 1fr;
    }
    .hr-container{
        display: grid;
        grid-template-columns: 5fr 1fr;
    }
    .agenda-detail-weekly-squedules{
    display: grid;
    grid-template-columns: 1fr 14fr 14fr 1fr;
    border-style: solid;
    border-width: 1px;

    }
    .agenda-detail-form{
    display: grid;
    grid-template-columns: 3fr 1fr;

    }
    
</style>

<div class="create-update-container">

    <div></div>

    <div>
        {% include 'base/partials/agenda-update.html' %}        
    </div>
    
    <div></div>
</div>


{% endblock content %}

{% block javascript %}

<script>
  
  $(document).ready(function(){
      mondayStatus()
      tuesdayStatus()
      wednesdayStatus()
      thursdayStatus()
      fridayStatus()
      saturdayStatus()
      sundayStatus()
  })

  // Monday checkbox
  function mondayStatus(event) {
  var text = document.getElementById("monday-text");
  var btn = document.getElementById("monday-add_btn");
  const currentForms = document.getElementsByClassName('monday-form')  
  if ($("#monday-checkbox").is(":checked")) {
      $(currentForms).show();
      text.style.display = "none";
      btn.style.display = "block";
  } else {
      $(currentForms).hide();
      text.style.display = "block";
      btn.style.display = "none";
  }
  };

  $(document).on("click", "#monday-checkbox", mondayStatus);

  // Tuesday checkbox
  function tuesdayStatus(event) {
  var text = document.getElementById("tuesday-text");
  var btn = document.getElementById("tuesday-add_btn");
  const currentForms = document.getElementsByClassName('tuesday-form')  
  if ($("#tuesday-checkbox").is(":checked")) {
      $(currentForms).show();
      text.style.display = "none";
      btn.style.display = "block";
  } else {
      $(currentForms).hide();
      text.style.display = "block";
      btn.style.display = "none";
  }
  };

  $(document).on("click", "#tuesday-checkbox", tuesdayStatus);

  // Wednesday checkbox
  function wednesdayStatus(event) {
  var text = document.getElementById("wednesday-text");
  var btn = document.getElementById("wednesday-add_btn");
  const currentForms = document.getElementsByClassName('wednesday-form')  
  if ($("#wednesday-checkbox").is(":checked")) {
      $(currentForms).show();
      text.style.display = "none";
      btn.style.display = "block";
  } else {
      $(currentForms).hide();
      text.style.display = "block";
      btn.style.display = "none";
  }
  };

  $(document).on("click", "#wednesday-checkbox", wednesdayStatus);

  // Thursday checkbox
  function thursdayStatus(event) {
  var text = document.getElementById("thursday-text");
  var btn = document.getElementById("thursday-add_btn");
  const currentForms = document.getElementsByClassName('thursday-form')  
  if ($("#thursday-checkbox").is(":checked")) {
      $(currentForms).show();
      text.style.display = "none";
      btn.style.display = "block";
  } else {
      $(currentForms).hide();
      text.style.display = "block";
      btn.style.display = "none";
  }
  };

  $(document).on("click", "#thursday-checkbox", thursdayStatus);

  // Friday checkbox
  function fridayStatus(event) {
  var text = document.getElementById("friday-text");
  var btn = document.getElementById("friday-add_btn");
  const currentForms = document.getElementsByClassName('friday-form')  
  if ($("#friday-checkbox").is(":checked")) {
      $(currentForms).show();
      text.style.display = "none";
      btn.style.display = "block";
  } else {
      $(currentForms).hide();
      text.style.display = "block";
      btn.style.display = "none";
  }
  };

  $(document).on("click", "#friday-checkbox", fridayStatus);

  // Saturday checkbox
  function saturdayStatus(event) {
  var text = document.getElementById("saturday-text");
  var btn = document.getElementById("saturday-add_btn");
  const currentForms = document.getElementsByClassName('saturday-form')  
  if ($("#saturday-checkbox").is(":checked")) {
      $(currentForms).show();
      text.style.display = "none";
      btn.style.display = "block";
  } else {
      $(currentForms).hide();
      text.style.display = "block";
      btn.style.display = "none";
  }
  };

  $(document).on("click", "#saturday-checkbox", saturdayStatus);

  // Sunday checkbox
  function sundayStatus(event) {
  var text = document.getElementById("sunday-text");
  var btn = document.getElementById("sunday-add_btn");
  const currentForms = document.getElementsByClassName('sunday-form')  
  if ($("#sunday-checkbox").is(":checked")) {
      $(currentForms).show();
      text.style.display = "none";
      btn.style.display = "block";
  } else {
      $(currentForms).hide();
      text.style.display = "block";
      btn.style.display = "none";
  }
  };

  $(document).on("click", "#sunday-checkbox", sundayStatus);

//   // Persist checkbox function
//   var checkboxValues = JSON.parse(localStorage.getItem('checkboxValues')) || {};
//   var $checkboxes = $("#checkbox-container :checkbox");

//   $checkboxes.on("change", function(){
//       $checkboxes.each(function(){
//           checkboxValues[this.id] = this.checked;
//       });
  
//       localStorage.setItem("checkboxValues", JSON.stringify(checkboxValues));
//   });

//   $.each(checkboxValues, function(key, value) {
//       $("#" + key).prop('checked', value);
//   });

</script>

{% endblock javascript %}

base/templates/base/calendar.html
{% extends 'main.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <div class="input-group date" id="datetimepicker14" data-target-input="nearest">
                    <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker14"/>
                    <div class="input-group-append" data-target="#datetimepicker14" data-toggle="datetimepicker">
                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker14').datetimepicker({
                    allowMultidate: true,
                    multidateSeparator: ','
                });
            });
        </script>
    </div>
</div>

{% endblock content %}

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}

<style>
    .group-container{
      display: grid;
      grid-template-columns: 1fr 6fr 1fr;
  
    }
</style>

<div class="group-container">
    <div></div>

    <div>
        <hr>
        <form method="POST" action="">
            {% csrf_token %}
            <p>Are you sure you want to dele "{{obj}}"?</p>
        
            <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
            <input type="submit" value="Confirm" />
        </form>
    </div>

    <div></div>

</div>

{% endblock content %}

base/templates/base/settings-VM-update.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

<style>
    .group-container{
      display: grid;
      grid-template-columns: 1fr 6fr 1fr;
  
    }
    .telegram-settings-container2{
      display: grid;
      grid-template-columns: 6fr;
  
    }

</style>

<div class="group-container">

    <div></div>
  
    <div class="content-section">
        <div class="telegram-settings-container2">
            <div>
                <spam style="float:left">
                    <h1>Voice messages</h1>
                </spam>
                <spam style="float:right">
                    <h3><a href="{% url 'telegram-settings-VM' %}">Go Back</a></h3>
                </spam>
            </div>
        </div> 
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
            <div id="event_name">
                {{ form.as_p }}
                <input type="Submit" value="Submit" />
            </div>
            </fieldset>
        </form>
    </div>
  
    <div></div>
  
</div>

{% endblock content %}

{% block javascript %}

<script>
  // Call hideShow when page is loaded
  $(document).ready(function(){
      hideShow()
  })

  // call hideShow when the user clicks on the time dropdownlist
  $('#id_voice_messages').click(function(){
      hideShow()
  });

  function hideShow(){
      if(document.getElementById('id_voice_messages').options[document.getElementById('id_voice_messages').selectedIndex].value == "")
      {
          $('#id_voice_messages_notification').parents('p:first').hide();
      }
      else if(document.getElementById('id_voice_messages').options[document.getElementById('id_voice_messages').selectedIndex].value == "inactivated") 
      {
        $('#id_voice_messages_notification').parents('p:first').hide();
      }
      else
      {
        $('#id_voice_messages_notification').parents('p:first').show();
      }
  }


</script>

{% endblock javascript %}